# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EstraiCatasto
                                 A QGIS plugin
 EstraiCatasto is a QGIS plugin designed to streamline the processing of Italian cadastral vector data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-03
        copyright            : (C) 2025 by Ludovico Frate
        email                : frateludovico@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EstraiCatasto class from file EstraiCatasto.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .estrai_catasto import EstraiCatasto
    return EstraiCatasto(iface)
